var TEXT_PRELOADER_CONTINUE = "START";
var TEXT_SCORE     = "SCORE";
var TEXT_ARE_SURE = "ARE YOU SURE?";
var TEXT_GAMEOVER = "CONGRATULATION! YOU WON THIS MATCH!";
var TEXT_LOSE = "PLAYER ";
var TEXT_LOSE2 = " WON THIS MATCH";
var TEXT_WIN_2PLAYERS = "PLAYER " ;
var TEXT_WIN_2PLAYERS_2 = " WON THIS MATCH";
var TEXT_SELECT_PLAYERS_MENU = "SELECT MODE";
var TEXT_NO_MOVES_AVAILABLE = "NO MOVES AVAILABLE, NEXT PLAYER WILL PLAY";
var TEXT_DOUBLE_DICES = "GOT A DOUBLE, DICES REDOUBLED";
var TEXT_THINKING = "THINKING";

var TEXT_RULEBROKEN_BOTH = "WITH THIS MOVE YOU CAN'T PLAY ALL DICES. PLEASE DO ANOTHER MOVES THAT ALLOWS YOU PLAY BOTH DICES";
var TEXT_RULEBROKEN_HIGHER = "WITH THIS MOVE YOU CAN'T PLAY THE DICE WITH HIGHER VALUE. PLEASE DO ANOTHER MOVE THAT ALLOWS YOU TO DO IT";

var TEXT_SHARE_IMAGE = "200x200.jpg";
var TEXT_SHARE_TITLE = "Congratulations!";
var TEXT_SHARE_MSG1 = "You collected <strong>";
var TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
var TEXT_SHARE_SHARE1 = "My score is ";
var TEXT_SHARE_SHARE2 = " points! Can you do better";